import type { Metadata } from "next";
import { Hanken_Grotesk } from "next/font/google";
import "./globals.css";

const hankenGrotesk = Hanken_Grotesk({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-hanken-grotesk', 
});

export const metadata: Metadata = {
  title: "Raij Mobi - Início",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="pt-BR"
      // Substituímos as fontes do Geist pela variável da sua Hanken Grotesk
      className={`${hankenGrotesk.variable} h-full antialiased`} 
    >
      <body className="min-h-full flex flex-col font-sans">
        <header></header>
        <aside></aside>
        <main>{children}</main>
        <footer></footer>
      </body>
    </html>
  );
}