// // // import type { Metadata } from "next";
// // // import { Geist, Geist_Mono } from "next/font/google";
// // // import "./globals.css";

// // // const geistSans = Geist({
// // //   variable: "--font-geist-sans",
// // //   subsets: ["latin"],
// // // });

// // // const geistMono = Geist_Mono({
// // //   variable: "--font-geist-mono",
// // //   subsets: ["latin"],
// // // });

// // // export const metadata: Metadata = {
// // //   title: "Create Next App",
// // //   description: "Generated by create next app",
// // // };

// // // export default function RootLayout({
// // //   children,
// // // }: Readonly<{
// // //   children: React.ReactNode;
// // // }>) {
// // //   return (
// // //     <html
// // //       lang="en"
// // //       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
// // //     >
// // //       <body className="min-h-full flex flex-col">{children}</body>
// // //     </html>
// // //   );
// // // }


// // import type { Metadata } from "next";
// // import "./globals.css";
// // import { Providers } from "./providers";

// // export const metadata: Metadata = {
// //   title: "Kiwidi • App Responsivo",
// //   description: "Caronas inteligentes",
// // };

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <html lang="pt-BR">
// //       <body>
// //         <Providers>{children}</Providers>
// //       </body>
// //     </html>
// //   );
// // }

// // import type { Metadata } from "next";
// // import "./globals.css";
// // import { Providers } from "./providers";
// // import { AppShell } from "@/components/templates/appShell";

// // export const metadata: Metadata = {
// //   title: "Kiwidi • App Responsivo",
// //   description: "Caronas inteligentes",
// // };

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   // Em um app real, você verificaria autenticação aqui.
// //   // Para simplicidade, sempre usa AppShell.
// //   return (
// //     <html lang="pt-BR">
// //       <body>
// //         <Providers>
// //           <AppShell>{children}</AppShell>
// //         </Providers>
// //       </body>
// //     </html>
// //   );
// // }


// import type { Metadata } from "next";
// import "./globals.css";
// import { Providers } from "./providers";

// export const metadata: Metadata = {
//   title: "Kiwidi • App Responsivo",
//   description: "Caronas inteligentes",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="pt-BR">
//       <head>
//         <link href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap" rel="stylesheet" />
//         <link href="https://fonts.googleapis.com/css2?family=Hanken+Grotesk:wght@400;600;700;800&family=Manrope:wght@400;500;600;700&display=swap" rel="stylesheet" />
//       </head>
//       <body>
//         <Providers>{children}</Providers>
//       </body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import "./globals.css";
import { css } from "@/styled-system/css"; 
import { Providers } from "./providers";
import { AppShell } from "@/components/templates/appShell";

export const metadata: Metadata = {
  title: "Kiwidi • App Responsivo",
  description: "Caronas inteligentes",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Hanken+Grotesk:wght@400;600;700;800&family=Manrope:wght@400;500;600;700&display=swap"
          rel="stylesheet"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:wght,FILL@100..700,0..1&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <Providers>
          <AppShell>{children}</AppShell>
        </Providers>
      </body>
    </html>
  );
}